version: '3'
services:
   db:
      image: mariadb
      container_name: laravel-login-workshop-db
      restart: always
      volumes:
         - ./.docker/mariadb:/var/lib/mysql
      env_file:
         - .env
      ports:
         - 3335:3306
      networks:
         - laravel-login-workshop-network

networks:
   laravel-login-workshop-network:
      name: laravel-login-workshop-network
      driver: bridge
